package frc.robot.constants;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;
import coppercore.parameter_tools.JSONExclude;
import coppercore.parameter_tools.JSONSync;
import coppercore.parameter_tools.JSONSyncConfigBuilder;
import coppercore.parameter_tools.path_provider.EnvironmentHandler;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class DrivetrainConstants {
  // Both sets of gains need to be tuned to your individual robot.

  public static final JSONSync<DrivetrainConstants> synced =
      new JSONSync<DrivetrainConstants>(
          new DrivetrainConstants(),
          "DrivetrainConstants.json",
          EnvironmentHandler.getEnvironmentHandler().getEnvironmentPathProvider(),
          new JSONSyncConfigBuilder().setPrettyPrinting(true).build());
  // The steer motor uses any SwerveModule.SteerRequestType control request with the
  // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput

  public static final Slot0Configs steerGains =
      new Slot0Configs()
          .withKP(40)
          .withKI(0)
          .withKD(0.0)
          .withKS(0.0)
          .withKV(0.0)
          .withKA(0.0)
          .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
  // When using closed-loop control, the drive motor uses the control
  // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput

  public static final Slot0Configs driveGains =
      new Slot0Configs().withKP(50.0).withKI(0.0).withKD(0).withKS(4.37713).withKV(2.87777);

  // The closed-loop output type to use for the steer motors;
  // This affects the PID/FF gains for the steer motors

  public static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
  // The closed-loop output type to use for the drive motors;
  // This affects the PID/FF gains for the drive motors

  public static final ClosedLoopOutputType kDriveClosedLoopOutput =
      ClosedLoopOutputType.TorqueCurrentFOC;

  // The type of motor used for the drive motor

  public static final DriveMotorArrangement kDriveMotorType =
      DriveMotorArrangement.TalonFX_Integrated;
  // The type of motor used for the drive motor

  public static final SteerMotorArrangement kSteerMotorType =
      SteerMotorArrangement.TalonFX_Integrated;

  // The remote sensor feedback type to use for the steer motors;
  // When not Pro-licensed, FusedCANcoder/SyncCANcoder automatically fall back to RemoteCANcoder

  public static final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.FusedCANcoder;

  // The stator current at which the wheels start to slip;
  // This needs to be tuned to your individual robot
  @JSONExclude public final Current kSlipCurrent = Amps.of(120.0);

  // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
  // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.

  public static final TalonFXConfiguration driveInitialConfigs =
      new TalonFXConfiguration()
          //   .withTorqueCurrent(
          //       new TorqueCurrentConfigs()
          //           .withPeakForwardTorqueCurrent(Amps.of(60))
          //           .withPeakReverseTorqueCurrent(Amps.of(60)))
          .withCurrentLimits(
              new CurrentLimitsConfigs()
                  // Swerve azimuth does not require much torque output, so we can set a relatively
                  // low
                  // stator current limit to help avoid brownouts without impacting performance.
                  .withSupplyCurrentLimit(Amps.of(60))
                  .withStatorCurrentLimit(Amps.of(80))
                  .withStatorCurrentLimitEnable(true));

  public final TalonFXConfiguration steerInitialConfigs =
      new TalonFXConfiguration()
          .withCurrentLimits(
              new CurrentLimitsConfigs()
                  // Swerve azimuth does not require much torque output, so we can set a relatively
                  // low
                  // stator current limit to help avoid brownouts without impacting performance.
                  .withStatorCurrentLimit(Amps.of(60))
                  .withStatorCurrentLimitEnable(true));

  public static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
  // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
  public final Pigeon2Configuration pigeonConfigs = null;

  // CAN bus that the devices are located on;
  // All swerve devices must share the same CAN bus
  public final CANBus kCANBus = new CANBus("canivore", "./logs/example.hoot");

  // Theoretical free speed (m/s) at 12 V applied output;
  // This needs to be tuned to your individual robot
  //   public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(4.69);
  @JSONExclude public final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(4.0);

  // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
  // This may need to be tuned to your individual robot
  public final double kCoupleRatio = 3.5714285714285716;

  public final double kDriveGearRatio = 5.142857;
  public final double kSteerGearRatio = 25.0;
  @JSONExclude public final Distance kWheelRadius = Inches.of(2.0);

  public final int kPigeonId = 20;

  // These are only used for simulation
  @JSONExclude public final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.00001);
  @JSONExclude public final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.001);
  // Simulated voltage necessary to overcome friction
  @JSONExclude public final Voltage kSteerFrictionVoltage = Volts.of(0.25);
  @JSONExclude private final Voltage kDriveFrictionVoltage = Volts.of(0.25);

  public final SwerveDrivetrainConstants DrivetrainConstants =
      new SwerveDrivetrainConstants()
          .withCANBusName(kCANBus.getName())
          .withPigeon2Id(kPigeonId)
          .withPigeon2Configs(pigeonConfigs);

  public final SwerveModuleConstantsFactory<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      ConstantCreator =
          new SwerveModuleConstantsFactory<
                  TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
              .withDriveMotorGearRatio(kDriveGearRatio)
              .withSteerMotorGearRatio(kSteerGearRatio)
              .withCouplingGearRatio(kCoupleRatio)
              .withWheelRadius(kWheelRadius)
              .withSteerMotorGains(steerGains)
              .withDriveMotorGains(driveGains)
              .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
              .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
              .withSlipCurrent(kSlipCurrent)
              .withSpeedAt12Volts(kSpeedAt12Volts)
              .withDriveMotorType(kDriveMotorType)
              .withSteerMotorType(kSteerMotorType)
              .withFeedbackSource(kSteerFeedbackType)
              .withDriveMotorInitialConfigs(driveInitialConfigs)
              .withSteerMotorInitialConfigs(steerInitialConfigs)
              .withEncoderInitialConfigs(encoderInitialConfigs)
              .withSteerInertia(kSteerInertia)
              .withDriveInertia(kDriveInertia)
              .withSteerFrictionVoltage(kSteerFrictionVoltage)
              .withDriveFrictionVoltage(kDriveFrictionVoltage);

  // Front Left
  public final int kFrontLeftDriveMotorId = 7;
  public final int kFrontLeftSteerMotorId = 8;
  public final int kFrontLeftEncoderId = 9;
  @JSONExclude public final Angle kFrontLeftEncoderOffset = Rotations.of(-0.267822265625);
  public final boolean kFrontLeftSteerMotorInverted = false;
  public final boolean kFrontLeftDriveMotorInverted = false;
  public final boolean kFrontLeftEncoderInverted = false;

  @JSONExclude public final Distance kFrontLeftXPos = Inches.of(10.75);
  @JSONExclude public final Distance kFrontLeftYPos = Inches.of(11.5);

  // Front Right
  public final int kFrontRightDriveMotorId = 1;
  public final int kFrontRightSteerMotorId = 2;
  public final int kFrontRightEncoderId = 12;
  @JSONExclude public final Angle kFrontRightEncoderOffset = Rotations.of(-0.228271484375);
  public final boolean kFrontRightSteerMotorInverted = false;
  public final boolean kFrontRightDriveMotorInverted = true;
  public final boolean kFrontRightEncoderInverted = false;

  @JSONExclude public final Distance kFrontRightXPos = Inches.of(10.75);
  @JSONExclude public final Distance kFrontRightYPos = Inches.of(-11.5);

  // Back Left
  public final int kBackLeftDriveMotorId = 5;
  public final int kBackLeftSteerMotorId = 6;
  public final int kBackLeftEncoderId = 10;
  @JSONExclude public final Angle kBackLeftEncoderOffset = Rotations.of(0.084716796875);
  public final boolean kBackLeftSteerMotorInverted = false;
  public final boolean kBackLeftDriveMotorInverted = true;
  public final boolean kBackLeftEncoderInverted = false;

  @JSONExclude public final Distance kBackLeftXPos = Inches.of(-10.75);
  @JSONExclude public final Distance kBackLeftYPos = Inches.of(11.5);

  // Back Right
  public final int kBackRightDriveMotorId = 3;
  public final int kBackRightSteerMotorId = 4;
  public final int kBackRightEncoderId = 11;
  @JSONExclude public final Angle kBackRightEncoderOffset = Rotations.of(0.39990234375);
  public final boolean kBackRightSteerMotorInverted = true;
  public final boolean kBackRightDriveMotorInverted = true;
  public final boolean kBackRightEncoderInverted = false;

  @JSONExclude public final Distance kBackRightXPos = Inches.of(-10.75);
  @JSONExclude public final Distance kBackRightYPos = Inches.of(-11.5);

  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      FrontLeft =
          ConstantCreator.createModuleConstants(
              kFrontLeftSteerMotorId,
              kFrontLeftDriveMotorId,
              kFrontLeftEncoderId,
              kFrontLeftEncoderOffset,
              kFrontLeftXPos,
              kFrontLeftYPos,
              kFrontLeftDriveMotorInverted,
              kFrontLeftSteerMotorInverted,
              kFrontLeftEncoderInverted);

  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      FrontRight =
          ConstantCreator.createModuleConstants(
              kFrontRightSteerMotorId,
              kFrontRightDriveMotorId,
              kFrontRightEncoderId,
              kFrontRightEncoderOffset,
              kFrontRightXPos,
              kFrontRightYPos,
              kFrontRightDriveMotorInverted,
              kFrontRightSteerMotorInverted,
              kFrontRightEncoderInverted);

  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      BackLeft =
          ConstantCreator.createModuleConstants(
              kBackLeftSteerMotorId,
              kBackLeftDriveMotorId,
              kBackLeftEncoderId,
              kBackLeftEncoderOffset,
              kBackLeftXPos,
              kBackLeftYPos,
              kBackLeftDriveMotorInverted,
              kBackLeftSteerMotorInverted,
              kBackLeftEncoderInverted);

  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      BackRight =
          ConstantCreator.createModuleConstants(
              kBackRightSteerMotorId,
              kBackRightDriveMotorId,
              kBackRightEncoderId,
              kBackRightEncoderOffset,
              kBackRightXPos,
              kBackRightYPos,
              kBackRightDriveMotorInverted,
              kBackRightSteerMotorInverted,
              kBackRightEncoderInverted);

  /**
   * Creates a CommandSwerveDrivetrain instance. This should only be called once in your robot
   * program,.
   */
  //   public static CommandSwerveDrivetrain createDrivetrain() {
  //     return new CommandSwerveDrivetrain(
  //         DrivetrainConstants, FrontLeft, FrontRight, BackLeft, BackRight);
  //   }

  /** Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected device types. */
  public class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * <p>This constructs the underlying hardware devices, so users should not construct the devices
     * themselves. If they need the devices, they can access them through getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules Constants for each specific module
     */
    public TunerSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
      super(TalonFX::new, TalonFX::new, CANcoder::new, drivetrainConstants, modules);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * <p>This constructs the underlying hardware devices, so users should not construct the devices
     * themselves. If they need the devices, they can access them through getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set
     *     to 0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
     * @param modules Constants for each specific module
     */
    public TunerSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules) {
      super(
          TalonFX::new,
          TalonFX::new,
          CANcoder::new,
          drivetrainConstants,
          odometryUpdateFrequency,
          modules);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * <p>This constructs the underlying hardware devices, so users should not construct the devices
     * themselves. If they need the devices, they can access them through getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set
     *     to 0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
     *     [x, y, theta]ᵀ, with units in meters and radians
     * @param visionStandardDeviation The standard deviation for vision calculation in the form [x,
     *     y, theta]ᵀ, with units in meters and radians
     * @param modules Constants for each specific module
     */
    public TunerSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules) {
      super(
          TalonFX::new,
          TalonFX::new,
          CANcoder::new,
          drivetrainConstants,
          odometryUpdateFrequency,
          odometryStandardDeviation,
          visionStandardDeviation,
          modules);
    }
  }
}
